name: "Test Suite"
on:
  push:
  pull_request:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          override: true
          toolchain: nightly
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast

  coverage:
      name: code coverage
      runs-on: ubuntu-latest
      steps:
        # the action needs a nightly toolchain with llvm-tools
        - uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: nightly
            override: true
            components: llvm-tools-preview
        # runs cargo with defaults flags, using the default `lcov` output
        - uses: Swatinem/fucov@v1
        - uses: codecov/codecov-action@v1
          with:
            directory: coverage

  # Check formatting with rustfmt
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
